# Generated by Django 3.1.7 on 2021-03-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(default='ron', max_length=122),
        ),
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(default='ie', max_length=122),
        ),
        migrations.AddField(
            model_name='contact',
            name='state',
            field=models.CharField(default='ie', max_length=122),
        ),
        migrations.AddField(
            model_name='contact',
            name='zip',
            field=models.CharField(default='ie', max_length=122),
        ),
    ]
